# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9be07f72fb84b525aa10364824cecb4c783365b832fdf8e42d30f7eec00b55a8a456f362c42f3fa69587529260211af5471ce6f99b94bca1cf140b2fd5664d1e

test:
  secret_key_base: 469c39fb799425fce12ccafa5e31deaf3069e89d134eb52fb69300963ac0ed69de7b9da42d1431b47a8ada5b61deac986d37dc197acb98f705fbf18091bcd480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
